CREATE DATABASE ProjetoVendas;
GO

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY NOT NULL,
    NOME_CATEGORIA VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY NOT NULL,
    CPF_CLIENTE VARCHAR(20) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT PRIMARY KEY NOT NULL,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE VENDAS (
    ID_VENDA INT PRIMARY KEY NOT NULL,
    DATA_VENDA DATE NOT NULL,
    ID_PRODUTO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);